url: binarandi.github.io
theme: minima
title: in its right place
author: Ghazi Binarandi
description: a collection of my half-baked thoughts
twitter_username: binarandi
timezone: "Asia/Jakarta"
future: true
